
// This is an autogenerated file from Firebase Studio.
'use server'; // Potentially, some functions might be used in Server Actions if needed, but primarily for client.

import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signOut as firebaseSignOut,
  updateProfile,
  type UserCredential,
  type User as FirebaseUser,
} from 'firebase/auth';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { auth, db } from './firebase';

export interface UserProfile {
  uid: string;
  email: string | null;
  firstName: string;
  lastName: string;
  displayName: string | null;
  createdAt: any; // Firebase ServerTimestamp
}

/**
 * Signs up a new user with email and password, and stores their profile in Firestore.
 */
export async function signUpWithEmailPassword(
  email: string,
  password: string,
  firstName: string,
  lastName: string
): Promise<FirebaseUser> {
  if (!auth || !db) {
    throw new Error('Firebase has not been initialized correctly.');
  }

  try {
    const userCredential: UserCredential = await createUserWithEmailAndPassword(auth, email, password);
    const user = userCredential.user;

    // Update Firebase Auth profile
    await updateProfile(user, {
      displayName: `${firstName} ${lastName}`,
    });

    // Create user document in Firestore
    const userRef = doc(db, 'users', user.uid);
    const userProfileData: UserProfile = {
      uid: user.uid,
      email: user.email,
      firstName,
      lastName,
      displayName: user.displayName,
      createdAt: serverTimestamp(),
    };
    await setDoc(userRef, userProfileData);

    return user;
  } catch (error: any) {
    console.error('Error signing up:', error);
    throw new Error(error.message || 'Failed to sign up.');
  }
}

/**
 * Signs in an existing user with email and password.
 */
export async function signInWithEmailPassword(email: string, password: string): Promise<FirebaseUser> {
  if (!auth) {
    throw new Error('Firebase Auth has not been initialized correctly.');
  }
  try {
    const userCredential: UserCredential = await signInWithEmailAndPassword(auth, email, password);
    return userCredential.user;
  } catch (error: any) {
    console.error('Error signing in:', error);
    throw new Error(error.message || 'Failed to sign in.');
  }
}

/**
 * Signs out the current user.
 */
export async function signOutUser(): Promise<void> {
  if (!auth) {
    throw new Error('Firebase Auth has not been initialized correctly.');
  }
  try {
    await firebaseSignOut(auth);
  } catch (error: any) {
    console.error('Error signing out:', error);
    throw new Error(error.message || 'Failed to sign out.');
  }
}
